# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/people.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import person_pb2 as protos_dot_person__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/people.proto',
  package='example',
  syntax='proto3',
  serialized_pb=_b('\n\x13protos/people.proto\x12\x07\x65xample\x1a\x13protos/person.proto\")\n\x06People\x12\x1f\n\x06person\x18\x01 \x03(\x0b\x32\x0f.example.Personb\x06proto3')
  ,
  dependencies=[protos_dot_person__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PEOPLE = _descriptor.Descriptor(
  name='People',
  full_name='example.People',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='example.People.person', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=94,
)

_PEOPLE.fields_by_name['person'].message_type = protos_dot_person__pb2._PERSON
DESCRIPTOR.message_types_by_name['People'] = _PEOPLE

People = _reflection.GeneratedProtocolMessageType('People', (_message.Message,), dict(
  DESCRIPTOR = _PEOPLE,
  __module__ = 'protos.people_pb2'
  # @@protoc_insertion_point(class_scope:example.People)
  ))
_sym_db.RegisterMessage(People)


# @@protoc_insertion_point(module_scope)
